theme: jekyll-theme-dinky

integration_spreadsheet_key: 2PACX-1vSWFL3X1yLCDoP4H7ei6eAK1UwkUxgZBv-_YJ4LvG5RKQz9T3eff8AuoX7_ysjyBSxqERaw-sd09i_k

github_user:TauqeerSaleem
github_repo:Gilgit-Baltistan-COVID19